### ISSUE TITLE
lightum stops working after suspend

### ISSUE THREAD

**Issue by rrthomas** [poliva/lightum#1] opened 2012-02-26 16:07 UTC
I'm running lightum 1.5 on Ubuntu precise on a MBA 4,2 with default settings. After resume, the keyboard lights up, and the lights don't go off. Starting a new instance of lightum works.

Thanks for this useful program!

**Comment by poliva** [comment] 2012-03-04 22:42
Are you switching users, or this is on a single account computer?

**Comment by rrthomas** [comment] 2012-03-04 23:32
Single account.

**Comment by poliva** [comment] 2012-03-06 18:36
Can't reproduce it on 11.10, and still haven't had time to switch to 12.04. 
Can you post output of 'lightum -v -f' when this happens?

**Comment by rrthomas** [comment] 2012-03-08 14:08
$ lightum -v -f
CONFIG:
    manualmode: 0
    queryscreensaver: 0
    maxbrightness: 255
    minbrightness: 0
    polltime: 800
    idleoff: 10

lightum v1.5 running in auto mode 
light_sensor: 23 idle_time: 0.014000 auto mode maxbrightness: 255 brightness: 5 current: 255
-> set keyboard brightness: -1 -> 5

light_sensor: 23 idle_time: 1.030000 auto mode maxbrightness: 255 brightness: 5
light_sensor: 27 idle_time: 1.831000 auto mode maxbrightness: 255 brightness: 4 current: 5
-> set keyboard brightness: 5 -> 4

light_sensor: 27 idle_time: 2.933000 auto mode maxbrightness: 255 brightness: 4
light_sensor: 27 idle_time: 3.735000 auto mode maxbrightness: 255 brightness: 4
light_sensor: 27 idle_time: 4.539000 auto mode maxbrightness: 255 brightness: 4
light_sensor: 27 idle_time: 5.342000 auto mode maxbrightness: 255 brightness: 4
light_sensor: 27 idle_time: 6.144000 auto mode maxbrightness: 255 brightness: 4
light_sensor: 27 idle_time: 6.945000 auto mode maxbrightness: 255 brightness: 4
light_sensor: 27 idle_time: 7.748000 auto mode maxbrightness: 255 brightness: 4
light_sensor: 27 idle_time: 8.549000 auto mode maxbrightness: 255 brightness: 4
light_sensor: 27 idle_time: 9.352000 auto mode maxbrightness: 255 brightness: 4
light_sensor: 27 idle_time: 10.154000 auto mode maxbrightness: 255 brightness: 0 current: 4
-> set keyboard brightness: 4 -> 0

light_sensor: 27 idle_time: 0.800000 auto mode maxbrightness: 255 brightness: 4 current: 0
-> set keyboard brightness: 0 -> 4

^CKilled!

**Comment by poliva** [comment] 2012-03-08 17:34
At which point the keyboard lights up? the log seems normal behavior, at which point was the computer suspended/resumed?

**Comment by rrthomas** [comment] 2012-03-08 21:51
Sorry, I think I misunderstood: I ran lightum -v -f after resuming. I think you wanted me to run it, suspend and resume, and then report what happened. I shall do that now.

**Comment by rrthomas** [comment] 2012-03-08 22:00
I ran again manually, suspending and resuming in the middle. Here is the log:

$ lightum -v -f
CONFIG:
    manualmode: 0
    queryscreensaver: 0
    maxbrightness: 255
    minbrightness: 0
    polltime: 800
    idleoff: 10

lightum v1.5 running in auto mode 
light_sensor: 3 idle_time: 0.018000 auto mode maxbrightness: 255 brightness: 42 current: 0
-> set keyboard brightness: -1 -> 42

light_sensor: 3 idle_time: 1.036000 auto mode maxbrightness: 255 brightness: 42
light_sensor: 3 idle_time: 1.838000 auto mode maxbrightness: 255 brightness: 42
light_sensor: 0 idle_time: 2.640000 auto mode maxbrightness: 255 brightness: 255 current: 42
-> set keyboard brightness: 42 -> 255

light_sensor: 0 idle_time: 4.972000 auto mode maxbrightness: 255 brightness: 255
light_sensor: 0 idle_time: 6.505000 auto mode maxbrightness: 255 brightness: 255
light_sensor: 0 idle_time: 7.477000 auto mode maxbrightness: 255 brightness: 255
light_sensor: 2 idle_time: 0.173000 auto mode maxbrightness: 255 brightness: 63 current: 0
-> Detected user brightness change, setting maxbrightness to 0
-> set keyboard brightness: 0 -> 1

light_sensor: 2 idle_time: 1.276000 auto mode maxbrightness: 4 brightness: 1
light_sensor: 2 idle_time: 0.872000 auto mode maxbrightness: 4 brightness: 1
light_sensor: 2 idle_time: 1.674000 auto mode maxbrightness: 4 brightness: 1

...and it continues like this.

**Comment by poliva** [comment] 2012-04-26 17:36
I upgraded to ubuntu precise today and was finally able to reproduce the issue, for some reason when coming out of a suspend ubuntu messes up with the keyboard brightness value and lightum believes it has been manually changed using the function keys, that's why it adjusts the maxbrightness value. I'll try to find the root cause of this and provide a fix ASAP.

**Comment by poliva** [comment] 2012-04-26 20:06
Thanks for the bug report, it's fixed in master:
Ubuntu 12.04 changes the brightness value when returning from a suspend, I've added an option to ignore those brightness changes (ignoreuser=1) which is enabled by default in the config file.

**Closed as completed by poliva** 2012-04-26 20:06 UTC
